FROM debian:12-slim

RUN  apt update && apt install -y mariadb-server
RUN  rm -rf /var/lib/apt/lists/*

RUN  mkdir -p /var/run/mysqld && \
     chown -R mysql:mysql /var/run/mysqld

COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY tools/mdb_script.sh /usr/local/bin/mdb_script.sh
RUN  chmod +x /usr/local/bin/mdb_script.sh

EXPOSE 3306

ENTRYPOINT ["/usr/local/bin/mdb_script.sh"]
CMD ["mysqld"]
