FROM debian:bookworm

RUN apt-get update \
  && apt-get install -y mariadb-server mariadb-client tini \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /var/lib/mysql/*

COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY tools/mdb_script.sh /usr/local/bin/mdb_script.sh

RUN chmod 755 /usr/local/bin/mdb_script.sh \
  && mkdir -p /run/mysqld \
  && chown -R mysql:mysql /run/mysqld

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/mdb_script.sh"]
CMD ["mariadbd"]