FROM debian:bookworm

RUN apt-get update && apt-get install -y php \
	php-fpm \
	php-mysql \
	curl \
	wget \
	unzip \
	mariadb-client

RUN wget https://fr.wordpress.org/wordpress-6.9.1-fr_FR.zip -P /tmp \
    && unzip /tmp/wordpress-6.9.1-fr_FR.zip -d /tmp \
    && mkdir -p /var/www/html \
    && cp -r /tmp/wordpress/. /var/www/html/ \
    && rm -rf /tmp/wordpress-6.9.1-fr_FR.zip /tmp/wordpress \
    && chown -R www-data:www-data /var/www/html
	
RUN sed -i 's|listen = /run/php/php8.2-fpm.sock|listen = 9000|' /etc/php/8.2/fpm/pool.d/www.conf

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar \
	&& mv wp-cli.phar /usr/local/bin/wp

COPY /tools/wd_script.sh /usr/local/bin/wd_script.sh

RUN chmod +x /usr/local/bin/wd_script.sh

ENTRYPOINT ["/usr/local/bin/wd_script.sh"]
